# Generated by Django 4.1.7 on 2023-04-09 10:12

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_comment_listing_remove_listing_bid_bid_bids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.expressions.Case, related_name='user_list', to='auctions.listing'),
        ),
    ]
